configserver:
    name: Docker Consul Service
    status: Connected to Consul Server running in Docker

jhipster:
    security:
        authentication:
            jwt:
                secret: my-secret-token
spring:
    cloud:
        consul:
            host: localhost
            port: 8500
